/* Canonical, platform-neutral story rules. The cloud copy is generated by scripts/sync-story-core.mjs. */
const STORY_ID = /^story-[a-z0-9-]{1,100}$/;
const copy = value => JSON.parse(JSON.stringify(value));
function fail(message) { throw new Error(message); }
function stable(value) {
  if (Array.isArray(value)) return '[' + value.map(stable).join(',') + ']';
  if (value && typeof value === 'object') return '{' + Object.keys(value).sort().filter(k => value[k] !== undefined).map(k => JSON.stringify(k) + ':' + stable(value[k])).join(',') + '}';
  return JSON.stringify(value);
}
function hash(text) {
  let a = 2166136261, b = 5381;
  for (const char of text) { a = Math.imul(a ^ char.charCodeAt(0), 16777619); b = Math.imul(b, 33) ^ char.charCodeAt(0); }
  return (a >>> 0).toString(36) + (b >>> 0).toString(36);
}
function title(value, max = 80) {
  if (typeof value !== 'string' || !value.trim() || value.trim().length > max) fail('名称不能为空，且不能超过 ' + max + ' 字');
  return value.trim();
}
function activeStory(state, id, includeDeleted = false) {
  if (typeof id !== 'string' || !STORY_ID.test(id)) fail('请先选择一本故事书');
  const story = (state.stories || []).find(s => s.id === id);
  if (!story || (!includeDeleted && story.deletedAt)) fail('这本故事书已不可用，请返回书架');
  return story;
}
function history(state, id) {
  return (state.manuscriptRevisions || []).filter(r => r.storyId === id).sort((a,b) => b.savedAt.localeCompare(a.savedAt) || b.id.localeCompare(a.id));
}
function current(state, id) {
  const story = activeStory(state, id);
  const revision = history(state, id).find(r => r.id === story.currentRevisionId);
  if (story.currentRevisionId && !revision) fail('书稿版本暂未加载完整，请重试');
  return { draft: revision && revision.draft, revisionId: revision ? revision.id : '', sourceFingerprint: revision ? revision.sourceFingerprint : '' };
}
function uniqueName(state, name, except) {
  if ((state.stories || []).some(s => s.id !== except && !s.deletedAt && s.title === name)) fail('已有同名故事，请换一个名称');
}
function memories(state, ids) {
  if (!Array.isArray(ids) || ids.length > 500 || !ids.every(id => typeof id === 'string' && id.length <= 120)) fail('记忆列表无效');
  if (ids.some(id => !state.contributions.some(m => m.id === id && !m.deletedAt && m.scope === 'personal'))) fail('所选记忆已不可用，请刷新后重试');
  return [...new Set(ids)];
}
function flatten(chapters) {
  const digits = '零一二三四五六七八九';
  const content = [];
  chapters.forEach((c,i) => {
    const n = i + 1, t = Math.floor(n/10), o = n%10;
    const number = n < 10 ? digits[n] : (t > 1 ? digits[t] : '') + '十' + (o ? digits[o] : '');
    content.push({text: (i ? '\n' : '') + '第' + number + '章' + (c.title.trim() ? '　' + c.title.trim() : '') + '\n\n'}, ...copy(c.content));
    const last = content[content.length - 1];
    if (typeof last.text !== 'string' || !last.text.endsWith('\n')) content.push({text:'\n'});
  });
  return {content, paragraphs: content.map(i => i.text || '').join('').split(/\n\s*\n/).map(t => t.trim()).filter(Boolean)};
}
function validateDraft(draft, story) {
  if (!draft || typeof draft !== 'object') fail('书稿无效');
  title(draft.title);
  if (!Array.isArray(draft.chapters) || draft.chapters.length > 30) fail('一本书最多 30 章');
  const seen = new Set(); let length = 0, pictures = 0;
  for (const c of draft.chapters) {
    if (!c || !/^chapter-[a-z0-9-]{1,60}$/.test(c.id) || seen.has(c.id)) fail('章节编号无效');
    seen.add(c.id);
    if (typeof c.title !== 'string' || c.title.length > 40 || !Array.isArray(c.memoryIds) || c.memoryIds.some(id => !story.memoryIds.includes(id))) fail('章节包含其他故事的记忆');
    if (!Array.isArray(c.content)) fail('章节内容无效');
    for (const item of c.content) {
      if (typeof item.text === 'string' && item.photoId === undefined) length += item.text.length;
      else if (typeof item.photoId === 'string' && /^photo-[a-z0-9-]{1,120}$/.test(item.photoId) && item.text === undefined) pictures++;
      else fail('图片或正文引用无效');
    }
    if (c.backdropImageId && !/^family_[0-9A-Za-z_-]{1,120}_img_req-[0-9a-z-]{8,60}$/.test(c.backdropImageId)) fail('底图编号无效');
  }
  if (length > 20000 || pictures > 9) fail('书稿最多 20000 字、9 张正文图片');
  if (stable(flatten(draft.chapters)) !== stable({content:draft.content, paragraphs:draft.paragraphs})) fail('章节和全文不一致');
}
function fingerprint(state, id) {
  const story = activeStory(state,id);
  return stable({storyId:id, mode:story.writingMode, sources:state.contributions.filter(m => story.memoryIds.includes(m.id) && !m.deletedAt).map(m => ({id:m.id,text:m.text,photoIds:m.photoIds || []})).sort((a,b)=>a.id.localeCompare(b.id))});
}
function apply(state, command, now = new Date().toISOString()) {
  if (!state.storyMigration || state.storyMigration.status !== 'active') fail('故事书迁移尚未完成，请先打开书架');
  const requestId = command.requestId;
  if (typeof requestId !== 'string' || !/^[a-zA-Z0-9-]{8,100}$/.test(requestId)) fail('请求编号无效');
  const requestFingerprint = stable(command);
  const existing = (state.storyOperations || {})[requestId];
  if (existing) {
    if (existing.fingerprint !== requestFingerprint) fail('请求编号冲突');
    return state;
  }
  const next = copy(state);
  let story;
  if (command.action === 'create') {
    if (!STORY_ID.test(command.storyId) || (next.stories || []).some(s => s.id === command.storyId)) fail('故事编号冲突');
    const name = title(command.title,40); uniqueName(next,name);
    if (!['objective','creative'].includes(command.writingMode)) fail('请选择记录模式');
    story = {id:command.storyId, familyId:command.familyId || '', title:name, bookTitle:name, writingMode:command.writingMode,
      memoryIds:memories(next,command.memoryIds || []), protagonistMemberIds:[], createdAt:now,updatedAt:now,version:0,currentRevisionId:''};
    next.stories = [...(next.stories || []),story];
  } else {
    story = activeStory(next,command.storyId,command.action === 'restore');
    if (command.expectedVersion !== story.version) fail('故事已有更新，请刷新后重试');
    if (command.action === 'update') {
      const patch = command.patch || {};
      if (patch.title !== undefined) { const name = title(patch.title,40); uniqueName(next,name,story.id); story.title = name; }
      if (patch.bookTitle !== undefined) story.bookTitle = title(patch.bookTitle);
      if (patch.writingMode !== undefined) {
        if (!['objective','creative'].includes(patch.writingMode)) fail('记录模式无效');
        story.writingMode = patch.writingMode;
      }
      if (patch.coverImageId !== undefined) {
        if (patch.coverImageId && !(story.imageIds || []).includes(patch.coverImageId)) fail('封面必须来自本书');
        story.coverImageId = patch.coverImageId;
      }
    } else if (command.action === 'link') {
      story.memoryIds = [...new Set([...story.memoryIds,...memories(next,command.memoryIds)])];
    } else if (command.action === 'delete') story.deletedAt = now;
    else if (command.action === 'restore') {
      const name = command.title === undefined ? story.title : title(command.title,40);
      uniqueName(next,name,story.id); story.title = name; delete story.deletedAt;
    } else if (command.action === 'resolveAsset') {
      const pending = next.storyMigration.pending.find(p => p.id === command.pendingId);
      if (!pending || pending.resolvedStoryId || !['image','image-job'].includes(pending.kind)) fail('此迁移资源已处理，请刷新');
      pending.resolvedStoryId = story.id;
      if (pending.kind === 'image' && pending.imageId) story.imageIds = [...new Set([...(story.imageIds || []),pending.imageId])];
    } else if (command.action === 'save' || command.action === 'resolve') {
      if ((story.currentRevisionId || '') !== command.expectedRevisionId) fail('已有更新的书稿，请重新加载');
      let revision = copy(command.revision);
      if (!revision || revision.storyId !== story.id || !/^revision-[a-zA-Z0-9-]{1,120}$/.test(revision.id)) fail('书稿编号无效');
      if ((next.manuscriptRevisions || []).some(r => r.id === revision.id)) fail('版本编号冲突');
      if (command.restoreRevisionId) {
        const source = history(next,story.id).find(r=>r.id===command.restoreRevisionId);
        if (!source) fail('不能恢复其他故事的版本');
        revision.draft = copy(source.draft);
      }
      if (command.action === 'resolve') {
        const pending = next.storyMigration.pending.find(p => p.id === command.pendingId);
        if (!pending || pending.resolvedStoryId) fail('此章节已处理，请刷新');
        const base = current(next,story.id).draft;
        const chapter = copy(pending.chapter);
        chapter.id = 'chapter-' + hash(pending.id);
        story.memoryIds = [...new Set([...story.memoryIds,...chapter.memoryIds])];
        const chapters = [...(base ? base.chapters : []),chapter];
        revision.draft = {title:story.bookTitle || story.title,chapters,...flatten(chapters),sourceCount:story.memoryIds.length,generatedAt:now,generationMode:'local-demo'};
        revision.sourceRevisionId = pending.sourceRevisionId;
        pending.resolvedStoryId = story.id;
      }
      validateDraft(revision.draft,story);
      revision.savedAt = now;
      revision.sourceFingerprint = fingerprint(next,story.id);
      next.manuscriptRevisions = [...(next.manuscriptRevisions || []),revision];
      story.currentRevisionId = revision.id; story.bookTitle = revision.draft.title;
    } else fail('不支持的故事操作');
  }
  story.version++; story.updatedAt = now;
  next.storyOperations = {...next.storyOperations,[requestId]:{fingerprint:requestFingerprint,storyId:story.id}};
  return next;
}

/* Deterministic projection: the originals remain untouched, including deleted histories. */
function migrate(state, familyId = '', now = new Date().toISOString()) {
  if (state.storyMigration && state.storyMigration.status === 'active') return state;
  const next = copy(state), stories = copy(state.stories || []), pending = [], projected = [];
  const byTitle = new Map(), bySource = new Map();
  const legacyMemories = [...state.contributions].sort((a,b)=>{
    const left=[(a.storyTitle || '').trim(),a.authorMemberId || '',a.id || ''].join('|');
    const right=[(b.storyTitle || '').trim(),b.authorMemberId || '',b.id || ''].join('|');
    return left.localeCompare(right);
  });
  for (const m of legacyMemories) {
    const name = (m.storyTitle || '').trim();
    if (!name || m.scope !== 'personal') continue;
    const sourceId=(m.authorMemberId || ('memory:'+m.id)).trim(), sourceKey=name+'|'+sourceId;
    let story = bySource.get(sourceKey);
    if (!story) {
      let id = 'story-t-' + hash(sourceKey), suffix = 0;
      while (stories.some(s=>s.id===id)) id = 'story-t-' + hash(sourceKey) + '-' + (++suffix);
      const sameTitle=byTitle.get(name) || [], title=sameTitle.length ? name+'（'+(sameTitle.length+1)+'）' : name;
      const removed = (state.deletedStories || []).find(d=>d.key==='story:'+name+':'+sourceId || d.key==='story:'+name || d.title===name);
      story = {id,familyId,title,bookTitle:title,writingMode:'objective',version:1,currentRevisionId:'',memoryIds:[],imageIds:[],protagonistMemberIds:[],createdAt:now,updatedAt:now,
        legacy:{...(m.authorMemberId ? {memberId:m.authorMemberId} : {}),storyTitle:name,previousShelfKey:'story:'+name},...(removed ? {deletedAt:removed.deletedAt} : {})};
      stories.push(story); sameTitle.push(story); byTitle.set(name,sameTitle); bySource.set(sourceKey,story);
    }
    story.memoryIds.push(m.id);
  }
  const revisions = (state.manuscriptRevisions || []).filter(r=>!r.storyId).slice();
  const legacyDrafts = {...state.legacyPersonalDrafts,...state.personalDrafts};
  for (const [memberId,draft] of Object.entries(legacyDrafts)) {
    if (!revisions.some(r=>r.memberId===memberId && stable(r.draft)===stable(draft))) revisions.push({id:'legacy-'+memberId,memberId,kind:'version',label:'原有书稿',savedAt:draft.generatedAt || '1970-01-01T00:00:00.000Z',sourceFingerprint:'',draft});
  }
  const memberLatest = new Map();
  revisions.sort((a,b)=>a.savedAt.localeCompare(b.savedAt) || a.id.localeCompare(b.id));
  for (const r of revisions) memberLatest.set(r.memberId,r.id);
  const draftImages = chapters => [...new Set(chapters.flatMap(c=>[...(c.backdropImageId ? [c.backdropImageId] : []),...c.content.flatMap(i=>i.photoId && i.photoId.startsWith('photo-ai-') ? [familyId+'_img_'+i.photoId.slice(9)] : [])]))];
  const currentCandidates = new Map();
  for (const r of revisions) {
    const chapters = r.draft.chapters || [{id:'chapter-1',title:r.draft.title || '',memoryIds:[],content:r.draft.content || [{text:(r.draft.paragraphs || []).join('\n\n')}]}];
    const groups = new Map();
    for (const c of chapters) {
      const candidates = c.memoryIds.map(id=>stories.filter(s=>s.memoryIds.includes(id)));
      const owner = candidates.length && candidates.every(a=>a.length===1 && a[0].id===candidates[0][0]?.id) ? candidates[0][0] : undefined;
      const titleMatches=byTitle.get(c.title.trim()) || [];
      const conflict = titleMatches.length > 0 && !titleMatches.some(story=>story.id===owner?.id);
      if (!owner || conflict) {
        pending.push({id:'pending-'+hash(r.id+'|'+c.id),sourceRevisionId:r.id,memberId:r.memberId,chapter:copy(c),reason:!c.memoryIds.length?'没有明确来源记忆':conflict?'章节名称与来源故事冲突':'来源涉及多本书或记忆已缺失'});
        continue;
      }
      groups.set(owner.id,[...(groups.get(owner.id)||[]),copy(c)]);
    }
    for (const story of stories) {
      const cs = groups.get(story.id) || [];
      if (!cs.length && !projected.some(p=>p.storyId===story.id && p.memberId===r.memberId)) continue;
      const id = 'revision-migrated-'+hash(r.id+'|'+story.id);
      const draft = {...copy(r.draft),title:story.bookTitle,chapters:cs,...flatten(cs)};
      const projection = {...copy(r),id,storyId:story.id,sourceRevisionId:r.id,draft};
      projected.push(projection);
      story.imageIds = [...new Set([...story.imageIds,...draftImages(cs)])];
      if (memberLatest.get(r.memberId)===r.id) currentCandidates.set(story.id,[...(currentCandidates.get(story.id)||[]),projection]);
    }
  }
  for (const story of stories) {
    const candidates = currentCandidates.get(story.id) || [];
    if (candidates.length === 1) story.currentRevisionId = candidates[0].id;
    else if (candidates.length > 1) {
      for (const r of candidates) for (const chapter of r.draft.chapters) pending.push({id:'pending-multi-'+hash(r.id+'|'+chapter.id),sourceRevisionId:r.sourceRevisionId,memberId:r.memberId,chapter:copy(chapter),reason:'多个旧档案同时包含这本书，请确认当前章节'});
    }
  }
  next.stories = stories;
  next.manuscriptRevisions = [...(next.manuscriptRevisions || []),...projected];
  next.storyMigration = {version:1,status:'active',pending};
  return next;
}
module.exports = {STORY_ID,stable,hash,activeStory,history,current,flatten,validateDraft,fingerprint,apply,migrate};
